const getGanttHtml = () => [
  '<!DOCTYPE html>',
  '<html lang="zh-Hant">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>動態甘特圖預覽</title>',
  '  <style>',
  '    :root {',
  '      color-scheme: light;',
  '      font-family: "Noto Sans TC", "PingFang TC", "Microsoft JhengHei", system-ui, sans-serif;',
  '      background: #f6f7fb;',
  '      color: #1d2530;',
  '    }',
  '',
  '    body {',
  '      margin: 0;',
  '      padding: 24px;',
  '    }',
  '',
  '    .container {',
  '      max-width: 1200px;',
  '      margin: 0 auto;',
  '      display: grid;',
  '      gap: 24px;',
  '    }',
  '',
  '    header {',
  '      background: #ffffff;',
  '      border-radius: 16px;',
  '      padding: 20px 24px;',
  '      box-shadow: 0 12px 24px rgba(12, 24, 38, 0.08);',
  '    }',
  '',
  '    h1 {',
  '      margin: 0 0 8px;',
  '      font-size: 24px;',
  '    }',
  '',
  '    p {',
  '      margin: 0;',
  '      color: #5c6776;',
  '    }',
  '',
  '    .card {',
  '      background: #ffffff;',
  '      border-radius: 16px;',
  '      padding: 20px 24px;',
  '      box-shadow: 0 12px 24px rgba(12, 24, 38, 0.08);',
  '    }',
  '',
  '    .grid {',
  '      display: grid;',
  '      gap: 16px;',
  '    }',
  '',
  '    label {',
  '      font-size: 14px;',
  '      color: #3c4654;',
  '    }',
  '',
  '    input[type="text"],',
  '    input[type="date"],',
  '    input[type="number"] {',
  '      width: 100%;',
  '      padding: 8px 10px;',
  '      border-radius: 10px;',
  '      border: 1px solid #dde3ea;',
  '      font-size: 14px;',
  '      box-sizing: border-box;',
  '    }',
  '',
  '    input[type="number"] {',
  '      text-align: right;',
  '    }',
  '',
  '    .row {',
  '      display: grid;',
  '      gap: 12px;',
  '      grid-template-columns: 2fr 1fr 1fr 1fr 1fr auto;',
  '      align-items: end;',
  '    }',
  '',
  '    .row button {',
  '      height: 38px;',
  '    }',
  '',
  '    .actions {',
  '      display: flex;',
  '      gap: 12px;',
  '      flex-wrap: wrap;',
  '    }',
  '',
  '    button {',
  '      border: none;',
  '      border-radius: 999px;',
  '      padding: 10px 18px;',
  '      background: #1c64f2;',
  '      color: #ffffff;',
  '      font-size: 14px;',
  '      cursor: pointer;',
  '    }',
  '',
  '    button.secondary {',
  '      background: #e9eef6;',
  '      color: #1d2530;',
  '    }',
  '',
  '    button.ghost {',
  '      background: transparent;',
  '      border: 1px solid #d9e0ea;',
  '      color: #4a5563;',
  '      padding: 8px 14px;',
  '      border-radius: 10px;',
  '    }',
  '',
  '    .gantt {',
  '      display: grid;',
  '      gap: 12px;',
  '    }',
  '',
  '    .gantt-header,',
  '    .gantt-row {',
  '      display: grid;',
  '      grid-template-columns: 220px 1fr;',
  '      gap: 16px;',
  '      align-items: center;',
  '    }',
  '',
  '    .gantt-header span {',
  '      font-size: 12px;',
  '      color: #7b8794;',
  '    }',
  '',
  '    .bar-track {',
  '      position: relative;',
  '      height: 32px;',
  '      border-radius: 12px;',
  '      background: #f1f4f9;',
  '      overflow: hidden;',
  '      border: 1px solid #e1e8f0;',
  '    }',
  '',
  '    .bar-plan {',
  '      position: absolute;',
  '      top: 6px;',
  '      height: 20px;',
  '      border-radius: 10px;',
  '      background: #b9d4ff;',
  '    }',
  '',
  '    .bar-actual {',
  '      position: absolute;',
  '      top: 10px;',
  '      height: 12px;',
  '      border-radius: 6px;',
  '      background: #1c64f2;',
  '    }',
  '',
  '    .meta {',
  '      display: flex;',
  '      justify-content: space-between;',
  '      font-size: 12px;',
  '      color: #667085;',
  '      margin-top: 6px;',
  '    }',
  '',
  '    .empty {',
  '      padding: 24px;',
  '      text-align: center;',
  '      color: #9aa4b2;',
  '      border: 1px dashed #d8dee6;',
  '      border-radius: 12px;',
  '    }',
  '',
  '    @media (max-width: 1024px) {',
  '      .row {',
  '        grid-template-columns: 1fr 1fr;',
  '      }',
  '',
  '      .gantt-header,',
  '      .gantt-row {',
  '        grid-template-columns: 1fr;',
  '      }',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  <div class="container">',
  '    <header>',
  '      <h1>動態甘特圖預覽</h1>',
  '      <p>輸入主題、WBS 與日期後，預計/實際進度會自動更新甘特圖。</p>',
  '    </header>',
  '',
  '    <section class="card grid">',
  '      <div>',
  '        <label for="projectTitle">專案主題</label>',
  '        <input id="projectTitle" type="text" placeholder="例如：CRM 上線計畫" />',
  '      </div>',
  '      <div class="actions">',
  '        <button id="addRow">新增 WBS 項目</button>',
  '        <button id="loadSample" class="secondary">載入範例</button>',
  '        <button id="clearAll" class="ghost">清空</button>',
  '      </div>',
  '    </section>',
  '',
  '    <section class="card">',
  '      <div class="grid" id="wbsList"></div>',
  '    </section>',
  '',
  '    <section class="card">',
  '      <div class="gantt" id="ganttView">',
  '        <div class="empty">尚未建立項目，請先新增 WBS。</div>',
  '      </div>',
  '    </section>',
  '  </div>',
  '',
  '  <template id="wbsRow">',
  '    <div class="row">',
  '      <div>',
  '        <label>WBS 項目</label>',
  '        <input type="text" class="wbs-name" placeholder="例如：需求訪談" />',
  '      </div>',
  '      <div>',
  '        <label>開始日</label>',
  '        <input type="date" class="wbs-start" />',
  '      </div>',
  '      <div>',
  '        <label>結束日</label>',
  '        <input type="date" class="wbs-end" />',
  '      </div>',
  '      <div>',
  '        <label>預計進度 %</label>',
  '        <input type="number" min="0" max="100" class="wbs-plan" value="0" />',
  '      </div>',
  '      <div>',
  '        <label>實際進度 %</label>',
  '        <input type="number" min="0" max="100" class="wbs-actual" value="0" />',
  '      </div>',
  '      <button class="ghost remove-row" type="button">移除</button>',
  '    </div>',
  '  </template>',
  '',
  '  <script>',
  '    const wbsList = document.getElementById("wbsList");',
  '    const ganttView = document.getElementById("ganttView");',
  '    const projectTitle = document.getElementById("projectTitle");',
  '    const rowTemplate = document.getElementById("wbsRow");',
  '',
  '    const parseDate = (value) => (value ? new Date(value + "T00:00:00") : null);',
  '    const dayMs = 24 * 60 * 60 * 1000;',
  '',
  '    const clamp = (value, min, max) => Math.max(min, Math.min(max, value));',
  '',
  '    const getRows = () => Array.from(wbsList.querySelectorAll(".row")).map((row) => {',
  '      const name = row.querySelector(".wbs-name").value.trim();',
  '      const start = parseDate(row.querySelector(".wbs-start").value);',
  '      const end = parseDate(row.querySelector(".wbs-end").value);',
  '      const plan = clamp(Number(row.querySelector(".wbs-plan").value || 0), 0, 100);',
  '      const actual = clamp(Number(row.querySelector(".wbs-actual").value || 0), 0, 100);',
  '      return { name, start, end, plan, actual };',
  '    });',
  '',
  '    const buildScale = (rows) => {',
  '      const dates = rows.flatMap((row) => [row.start, row.end]).filter(Boolean);',
  '      if (!dates.length) return null;',
  '      const minDate = new Date(Math.min(...dates.map((date) => date.getTime())));',
  '      const maxDate = new Date(Math.max(...dates.map((date) => date.getTime())));',
  '      const spanDays = Math.max(1, Math.round((maxDate - minDate) / dayMs) + 1);',
  '      return { minDate, maxDate, spanDays };',
  '    };',
  '',
  '    const render = () => {',
  '      const rows = getRows();',
  '      const title = projectTitle.value.trim() || "未命名專案";',
  '',
  '      if (!rows.length) {',
  '        ganttView.innerHTML = "<div class=\"empty\">尚未建立項目，請先新增 WBS。</div>";',
  '        return;',
  '      }',
  '',
  '      const scale = buildScale(rows);',
  '      if (!scale) {',
  '        ganttView.innerHTML = "<div class=\"empty\">請填寫至少一筆開始/結束日期。</div>";',
  '        return;',
  '      }',
  '',
  '      const { minDate, maxDate, spanDays } = scale;',
  '      const header = `',
  '        <div class="gantt-header">',
  '          <strong>${title}</strong>',
  '          <span>${minDate.toLocaleDateString()} - ${maxDate.toLocaleDateString()}（共 ${spanDays} 天）</span>',
  '        </div>',
  '      `;',
  '',
  '      const rowsHtml = rows.map((row) => {',
  '        if (!row.start || !row.end) {',
  '          return `',
  '            <div class="gantt-row">',
  '              <div>${row.name || "未命名項目"}</div>',
  '              <div class="bar-track"></div>',
  '              <div class="meta">',
  '                <span>請補齊日期</span>',
  '                <span>預計 ${row.plan}% / 實際 ${row.actual}%</span>',
  '              </div>',
  '            </div>',
  '          `;',
  '        }',
  '',
  '        const start = Math.min(row.start.getTime(), row.end.getTime());',
  '        const end = Math.max(row.start.getTime(), row.end.getTime());',
  '        const offsetDays = Math.round((start - minDate.getTime()) / dayMs);',
  '        const durationDays = Math.max(1, Math.round((end - start) / dayMs) + 1);',
  '        const offsetPercent = (offsetDays / spanDays) * 100;',
  '        const durationPercent = (durationDays / spanDays) * 100;',
  '        const actualPercent = clamp(row.actual, 0, 100);',
  '        const planPercent = clamp(row.plan, 0, 100);',
  '',
  '        return `',
  '          <div class="gantt-row">',
  '            <div>',
  '              <div><strong>${row.name || "未命名項目"}</strong></div>',
  '              <div class="meta">',
  '                <span>${row.start.toLocaleDateString()} - ${row.end.toLocaleDateString()}</span>',
  '                <span>預計 ${planPercent}% / 實際 ${actualPercent}%</span>',
  '              </div>',
  '            </div>',
  '            <div class="bar-track">',
  '              <div',
  '                class="bar-plan"',
  '                style="left: ${offsetPercent}%; width: ${durationPercent}%;"',
  '                title="預計進度 ${planPercent}%"',
  '              ></div>',
  '              <div',
  '                class="bar-actual"',
  '                style="left: ${offsetPercent}%; width: ${(durationPercent * actualPercent) / 100}%;"',
  '                title="實際進度 ${actualPercent}%"',
  '              ></div>',
  '            </div>',
  '          </div>',
  '        `;',
  '      }).join("");',
  '',
  '      ganttView.innerHTML = `${header}${rowsHtml}`;',
  '    };',
  '',
  '    const addRow = (data = {}) => {',
  '      const fragment = rowTemplate.content.cloneNode(true);',
  '      const row = fragment.querySelector(".row");',
  '      row.querySelector(".wbs-name").value = data.name || "";',
  '      row.querySelector(".wbs-start").value = data.start || "";',
  '      row.querySelector(".wbs-end").value = data.end || "";',
  '      row.querySelector(".wbs-plan").value = data.plan ?? 0;',
  '      row.querySelector(".wbs-actual").value = data.actual ?? 0;',
  '',
  '      row.querySelector(".remove-row").addEventListener("click", () => {',
  '        row.remove();',
  '        render();',
  '      });',
  '',
  '      row.querySelectorAll("input").forEach((input) => {',
  '        input.addEventListener("input", render);',
  '        input.addEventListener("change", render);',
  '      });',
  '',
  '      wbsList.appendChild(fragment);',
  '      render();',
  '    };',
  '',
  '    document.getElementById("addRow").addEventListener("click", () => addRow());',
  '    document.getElementById("clearAll").addEventListener("click", () => {',
  '      wbsList.innerHTML = "";',
  '      projectTitle.value = "";',
  '      render();',
  '    });',
  '    document.getElementById("loadSample").addEventListener("click", () => {',
  '      wbsList.innerHTML = "";',
  '      projectTitle.value = "新產品上線專案";',
  '      addRow({ name: "需求訪談", start: "2024-06-01", end: "2024-06-10", plan: 100, actual: 100 });',
  '      addRow({ name: "系統設計", start: "2024-06-11", end: "2024-06-20", plan: 80, actual: 60 });',
  '      addRow({ name: "前後端開發", start: "2024-06-21", end: "2024-07-20", plan: 45, actual: 30 });',
  '      addRow({ name: "測試與上線", start: "2024-07-21", end: "2024-08-05", plan: 20, actual: 0 });',
  '    });',
  '',
  '    projectTitle.addEventListener("input", render);',
  '    render();',
  '  </script>',
  '</body>',
  '</html>',
].join('\n');

export default getGanttHtml;
